### PR TITLE
1.15.1 Support

### PR DESCRIPTION
**Pull request by LuminaSapphira**
Updated to 1.15.1. There seems to now be a boolean passed to `setPlayerSpawn` that lets it know whether the player set their spawn point using a bed, and I've swapped to using that. As a result, there may be some dead code for tracking that a maintainer should look over and verify if it is necessary. 

Also added a feature where a player can set their spawn point during day by sneak+using a bed. This prevents accidental setting of the spawn point if, for example, a player is spamming right-click on a bed as dusk approaches. If there is no set spawn point, it will be set regardless of sneaking.

Tested on 1.15.1 SP and Dedicated MP.

There didn't seem to be a 1.15 branch so I set it to merge into 1.14, though that may or may not be desirable.

### CODE REVIEW

**Comment by NikitaCartes** [comment]
Do you have .jar file, which can be used in game?

**Comment by LuminaSapphira** [comment]
Running `./gradlew build` on my fork should produce a runnable jar file

**Comment by modmuss50** [comment]
Sorry, only just seen this. I will take a look shortly. 

You should have poke me on discord ;)

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
thanks for this

**Pull request merged**
